# Generated by Django 4.0.1 on 2022-04-21 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('name', models.CharField(max_length=150)),
                ('number_of_bulks', models.IntegerField(default=0)),
                ('about_to_start', models.BooleanField(default=False)),
                ('as_started', models.BooleanField(default=False)),
                ('starting_date', models.DateTimeField(blank=True, null=True, verbose_name='starting date')),
                ('payment_expired', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='New_subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=150, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unappove_course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='testing_images/')),
                ('name', models.CharField(max_length=150)),
                ('about_to_start', models.BooleanField(default=False)),
                ('as_started', models.BooleanField(default=False)),
                ('starting_date', models.DateTimeField(blank=True, null=True, verbose_name='starting date')),
                ('payment_expired', models.BooleanField(default=False)),
                ('approve', models.BooleanField(default=False)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='learning.course')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.course')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=150, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('avatar', models.ImageField(blank=True, default='avatar.png', null=True, upload_to='user_img/')),
                ('ipaddress', models.CharField(max_length=16)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('device_type', models.CharField(max_length=150)),
                ('bio', models.TextField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('FR', 'Free'), ('PE', 'Premium'), ('PR', 'Pro'), ('EN', 'Enterprise')], default='FR', max_length=2)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('discount', models.FloatField(blank=True, null=True)),
                ('expired_date', models.DateTimeField()),
                ('allow_to_watch_download_video', models.BooleanField(default=False)),
                ('allow_to_live_class', models.BooleanField(default=False)),
                ('access_assignment', models.BooleanField(default=False)),
                ('allow_to_access_career_page', models.BooleanField(default=False)),
                ('get_access_certificate', models.BooleanField(default=False)),
                ('get_access_forum', models.BooleanField(default=False)),
                ('get_access_editor', models.BooleanField(default=False)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='learning.course')),
            ],
        ),
        migrations.CreateModel(
            name='Payed_class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('np', 'not paided'), ('pg', 'pending'), ('ep', 'expired'), ('pd', 'paid')], default='np', max_length=2)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='learning.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='News_for_new_subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sending_to', models.CharField(choices=[('al', 'all'), ('st', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='learning.new_subscriber'))], default='al', max_length=2)),
                ('heading', models.CharField(blank=True, max_length=150, null=True)),
                ('new', models.TextField(blank=True, null=True)),
                ('send_date', models.DateTimeField(blank=True, null=True)),
                ('send', models.BooleanField(default=False)),
                ('send_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='learning.new_subscriber')),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='teams/')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.course')),
            ],
        ),
        migrations.CreateModel(
            name='Frequently_asked_question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=150, null=True)),
                ('answer', models.TextField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.course')),
            ],
        ),
        migrations.CreateModel(
            name='Bulked_class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulk_at', models.DateTimeField(auto_now_add=True)),
                ('is_pay', models.BooleanField(default=False)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='learning.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
