# Generated by Django 4.0.4 on 2022-05-05 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_instructor_facebook_instructor_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='color',
            field=models.CharField(choices=[('pr', 'primary'), ('se', 'secondary'), ('da', 'danger'), ('dk', 'dark'), ('lt', 'light')], default='pr', max_length=2),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('Free', 'FR'), ('Premium', 'PE'), ('Pro', 'PR'), ('Enterprise', 'EN')], default='Free', max_length=10),
        ),
    ]
