# Generated by Django 4.0.4 on 2022-05-06 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_payment_color_alter_payment_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='color',
            field=models.CharField(choices=[('primary', 'primary'), ('secondary', 'secondary'), ('danger', 'danger'), ('dark', 'dark'), ('light', 'light')], default='primary', max_length=9),
        ),
    ]
