# Generated by Django 4.0.4 on 2022-05-12 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_coupon_remove_profile_device_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payed_class',
            old_name='timestamp',
            new_name='start_date',
        ),
        migrations.AddField(
            model_name='payed_class',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payed_class',
            name='ordered_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
