# Generated by Django 4.0.4 on 2022-05-12 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0007_rename_timestamp_payed_class_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payed_class',
            name='ref_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
