# Generated by Django 4.0.4 on 2022-05-13 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0009_profile_brower_version_profile_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='statisfy',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
