# Generated by Django 4.0.4 on 2022-05-13 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0011_alter_profile_latitude_alter_profile_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='error',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ipaddress',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='latitude',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='longitude',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
