# Generated by Django 4.0.4 on 2022-05-17 21:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning', '0015_payed_class_address2_payed_class_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payed_class',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Expire_class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('fname', models.CharField(max_length=150, null=True)),
                ('lname', models.CharField(max_length=150, null=True)),
                ('uname', models.CharField(max_length=150, null=True)),
                ('email', models.CharField(max_length=150, null=True)),
                ('address2', models.TextField(null=True)),
                ('city', models.CharField(max_length=150, null=True)),
                ('state', models.CharField(max_length=150, null=True)),
                ('country', models.CharField(max_length=150, null=True)),
                ('zip', models.CharField(max_length=150, null=True)),
                ('payment_mode', models.CharField(max_length=150, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('ordered_date', models.DateTimeField(blank=True, null=True)),
                ('expired_date', models.DateTimeField(default=datetime.datetime(2022, 5, 17, 22, 11, 27, 207358))),
                ('expired', models.BooleanField(default=True)),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='learning.coupon')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='learning.course')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='learning.payment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
