# Generated by Django 4.0.4 on 2022-05-17 21:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0016_alter_payed_class_start_date_expire_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expire_class',
            name='expired_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 17, 22, 35, 49, 849395)),
        ),
        migrations.AlterField(
            model_name='expire_class',
            name='user',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
