# Generated by Django 4.0.4 on 2022-05-17 21:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0017_alter_expire_class_expired_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expire_class',
            name='user',
        ),
        migrations.AlterField(
            model_name='expire_class',
            name='expired_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 17, 22, 42, 12, 57195)),
        ),
    ]
