# Generated by Django 4.0.4 on 2022-05-17 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0019_expire_class_user_alter_expire_class_expired_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expire_class',
            name='expired_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
