# Generated by Django 4.0.4 on 2022-06-03 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0020_alter_expire_class_expired_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zoom_information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=100)),
                ('secret_key', models.CharField(max_length=100)),
                ('zoom_email_address', models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='zoom_classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_time', models.DateTimeField()),
                ('duration', models.TimeField()),
                ('has_started', models.BooleanField(default=False)),
                ('has_ended', models.BooleanField(default=False)),
                ('about_to_start', models.BooleanField(default=False)),
                ('zoom_url', models.URLField(max_length=1000)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.course')),
            ],
        ),
        migrations.CreateModel(
            name='Create_class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('topic', models.CharField(max_length=150)),
                ('duration', models.TimeField(max_length=150)),
                ('password', models.CharField(max_length=150)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.course')),
            ],
        ),
    ]
