# Generated by Django 4.0.4 on 2022-06-04 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0021_zoom_information_zoom_classes_create_class'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zoom_classes',
            old_name='about_to_start',
            new_name='next_to_start',
        ),
        migrations.RemoveField(
            model_name='zoom_classes',
            name='starting_time',
        ),
        migrations.RemoveField(
            model_name='zoom_classes',
            name='zoom_url',
        ),
        migrations.AddField(
            model_name='zoom_classes',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='zoom_classes',
            name='host_email',
            field=models.EmailField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='zoom_classes',
            name='join_url',
            field=models.URLField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='zoom_classes',
            name='password',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='zoom_classes',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='zoom_classes',
            name='start_url',
            field=models.URLField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='zoom_classes',
            name='topic',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='zoom_classes',
            name='zoom_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='zoom_classes',
            name='duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='zoom_information',
            name='api_key',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='zoom_information',
            name='secret_key',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='zoom_information',
            name='zoom_email_address',
            field=models.EmailField(max_length=50, null=True),
        ),
    ]
