# Generated by Django 4.0.4 on 2022-06-04 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0022_rename_about_to_start_zoom_classes_next_to_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_class',
            name='duration',
            field=models.IntegerField(),
        ),
    ]
