# Generated by Django 4.0.4 on 2022-06-11 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0023_alter_create_class_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='payed_class',
            name='update_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
