# Generated by Django 4.0.4 on 2022-06-11 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0024_payed_class_update_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='learning.course'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='verlied',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
