# Generated by Django 4.0.4 on 2022-06-15 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0025_coupon_course_coupon_verlied'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoom_information',
            name='sdk_key',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='zoom_information',
            name='sdk_secret',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
