# Generated by Django 4.0.4 on 2022-06-15 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0026_zoom_information_sdk_key_zoom_information_sdk_secret'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zoom_information',
            name='sdk_secret',
        ),
    ]
