# Generated by Django 4.0.4 on 2022-06-15 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0027_remove_zoom_information_sdk_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoom_information',
            name='verification_token',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
