# Generated by Django 4.0.4 on 2022-06-16 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0028_zoom_information_verification_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='subscribe_class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True)),
                ('email', models.EmailField(max_length=150, null=True)),
            ],
        ),
    ]
