# Generated by Django 4.0.4 on 2022-06-16 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0029_subscribe_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe_class',
            name='email',
            field=models.EmailField(max_length=150, null=True, unique=True),
        ),
    ]
