# Generated by Django 4.0.4 on 2022-07-02 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0030_alter_subscribe_class_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='zoomUserName',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
